### ISSUE TITLE
Any chance we can get a License attached to the work?

### ISSUE THREAD

**Issue by byjrack** [domgiles/swingbench-public#10]
I know in the FAQ it talks to "free as is", but lots of ambiguity our lawyers don't love.  Would be a big help to just know the terms we can use the source and the compiled releases under.  Based on the comment in the FAQ it seems like MIT might be a fine option, but anything OSI would be awesome.

**Comment by domgiles** [comment]
I keep meaning to look into this. I'll look at the MIT one again.
