### ISSUE TITLE
error ORA-06502/ORA-0512

### ISSUE THREAD

**Issue by likingzi** [domgiles/swingbench-public#11]
When I perform swingbech on 19c, I met an error ORA-06502/ORA-0512, it looks like below(I typed them here):

java.sqlSQLException: ORA-06502: PLSQL numeric or value error number precision too large
ORA-06512: at "SOE.ORDERENTRY" line 1028
ORA-06512: at "SOE.ORDERENTRY" line 1019
An error described on the previous line has occcured. Further occurences will be supressed but the error count will be incremented and recorded in the results file
![ocr](https://user-images.githubusercontent.com/8468677/97267414-16e80500-1865-11eb-8a24-51c14d84b50f.JPG)

**Comment by likingzi** [comment]
note: I use SOE_server_size_V2 to perform the test

**Comment by domgiles** [comment]
I'll take a look. Sorry for the delay.

**Comment by jhorcl** [comment]
I think it's

`alter table orders modify (order_total number(10,2));`

or any size you want. Default of order_total is "(8,2)" but this is to small.

**Comment by domgiles** [comment]
Odd not seen it before..... I've updated it... I'll try and get a new build out this week.

**Comment by likingzi** [comment]
thx for your apply
