### ISSUE TITLE
NullPointerException oewizard graphical mode

### ISSUE THREAD

**Issue by swirkens** [domgiles/swingbench-public#19]
Hi,

I'm having issues running oewizard in graphical mode both on linux and windows.

Swingbench Version 2.6.0.1148
`./oewizard`  and `oewizard.bat` output:

> java.lang.NullPointerException
>     at javax.swing.ImageIcon.<init>(Unknown Source)
>         at com.dom.benchmarking.swingbench.wizards.soedg.Step5.$$$setupUI$$$(Step5.java)
>         at com.dom.benchmarking.swingbench.wizards.soedg.Step5.<init>(Step5.java:37)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
>         at java.lang.reflect.Constructor.newInstance(Unknown Source)
>         at java.lang.Class.newInstance(Unknown Source)
>         at com.dom.benchmarking.swingbench.wizards.WizardFrame.loadStepPanels(WizardFrame.java:123)
>         at com.dom.benchmarking.swingbench.wizards.WizardFrame.<init>(WizardFrame.java:49)
>         at com.dom.benchmarking.swingbench.wizards.WizardGuiLauncher$1.run(WizardGuiLauncher.java:24)
>         at java.awt.event.InvocationEvent.dispatch(Unknown Source)
>         at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
>         at java.awt.EventQueue.access$500(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.awt.EventQueue.dispatchEvent(Unknown Source)
>         at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by abcd0086** [comment]
Me too.
I have the same issue.

**Comment by swirkens** [comment]
@abcd0086
I found a way to get it working with **cloud database** using oewizard in console mode.

Command I used:
```
./oewizard -cl -create -dba admin -dbap strongPassword1 -u SOE -ts DATA -p strongPassword1 -cf Wallet_mgr21c.zip -cs "(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.eu-frankfurt-1.oraclecloud.com))(connect_data=(service_name=g308aff324ace93_mgr21c_tpurgent.adb.oraclecloud.com))(security=(ssl_server_cert_dn=\"CN=adwc.eucom-central-1.oraclecloud.com, OU=Oracle BMCS FRANKFURT, O=Oracle Corporation, L=Redwood City, ST=California, C=US\")))" -async_off -debug
```

1. You have to use **-async_off** option, otherwise it will create just the tables and throw errors while inserting data
2. You have to use **-ts DATA**. It will throw errors without this param
3. Note that **"** characters in connection string have to be escaped with backslash  **\\"**

```
. . . (ssl_server_cert_dn=\"CN=adwc.eucom-central-1.oraclecloud.com . . .
```


Tested on linux and windows and it's working only on linux

**Comment by chulminkw** [comment]
I have the same issue on oewizard.bat

Graphical mode for oewizard is not working and it seems like swing image file is not well located. 
(java.lang.NullPointerException at javax.swing.ImageIcon.(Unknown Source) )

**Comment by domgiles** [comment]
I have fixed the issue with async off in the upcoming build. It will now check whether its running against ADB and disable async.

I've also fixed the icon issue. I'll try and ship the new build tonight.
