### ISSUE TITLE
Unable to use GUI on Cloud Compute Node with X11 Forwarding

### ISSUE THREAD

**Issue by fkobylan** [domgiles/swingbench-public#7]
I'm attempting to use GUI Swingbench on a cloud based compute node.  I have X11 fowarding setup to ship the UI back to a hosted node.   I have installed X11 auth on the compute, modified sshd_config for X11 forwarding and modified my hosted box for the same.  I am able to run xclock on the compute node and have it display on my hosted box VNC but swingbench always returns an error.  I've tried this with 2 different versions, 2.6.0.1090 and 2.6.0.1124

$ ssh oracle@adg_compute -Y /home/oracle/swing2/swingbench/bin/swingbench
Application :    Swingbench
Author      :    Dominic Giles
Version     :    2.6.0.1090

Error : You're trying to start swingbench on a server without a graphical frontend. Try using charbench instead.

I'm able to do the X11 forwarding for swingbench from a database node in another environment to the same hosted VNC without issue.  I've compared X|x11 rpms installed and there's no appreciable difference.  There's no difference in the .ssh/config entries for the two environments where swingbench is being executed.  

What exactly is swingbench looking for or trying when it returns the error message above?  All of the debugging we do doesn't give us any indication what it thinks is missing or incorrect.  There's nothing in the debug log as well.

**Comment by domgiles** [comment]
I'll take a look... This happens during a swingbench check against the OS to determine whether it can render graphically. The exception that is generated is ```java.awt.HeadlessException```. So it's the JVM that doesn't think it can do it. 

Which JVM did you install?

**Comment by fkobylan** [comment]
$ java -version
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)

**Comment by domgiles** [comment]
Do you know if it was the headless or non headless version? There's 2 versions

**Comment by fkobylan** [comment]
It appears to be headless.  This is what I installed.

yum install java-1.8.0-openjdk-headless.x86_64

**Comment by fkobylan** [comment]
It looks like that was it.  I removed the headless version and installed java-1.8.0-openjdk.x86_64.  Works like a champ now, ableit slowly.  The compute is in Asia, my hosted box US but I'll take it.

**Comment by fkobylan** [comment]
I just realized the page with the instructions says to use the headless version.

http://www.dominicgiles.com/blog/files/c84a63640d52961fc28f750570888cdc-169.html

So I'm not 100% sure why it doesn't work with headless.

**Comment by domgiles** [comment]
The assumption is that most people will run a compute node headless.... i.e. only run character mode.

But you're right. The doc should indicate that if you take this approach a graphical swingbench wont work.
